# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rbf.io
subtitle: rather be functional
email: hi@rbf.io
description: >
  We make functional software.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://rbf.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
github_username: rbf

# Build settings
markdown: kramdown
permalink: pretty # SOURCE: https://jekyllrb.com/docs/permalinks/#built-in-permalink-styles
timezone: Europa/Zurich

# SOURCE: https://github.com/planetjekyll/awesome-jekyll-themes
theme: minima # default
# theme: jekyll-swiss # https://github.com/broccolini/swiss

google_analytics: UA-42657236-4

gems:
  # - jekyll-avatar       # does not work :( https://github.com/benbalter/jekyll-avatar
  - jekyll-feed           # SOURCE: https://github.com/jekyll/jekyll-feed
  - jemoji                # SOURCE: https://github.com/jekyll/jemoji
  - jekyll-mentions       # SOURCE: https://github.com/jekyll/jekyll-mentions
  - jekyll-redirect-from  # SOURCE: https://github.com/jekyll/jekyll-redirect-from
  - jekyll-sitemap        # SOURCE: https://github.com/jekyll/jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - git-untracked

include:
  - ".well-known" # SOURCE: https://josh.st/2015/10/22/jekyll-well-known-and-dotfiles/

# DOC: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      type: 'posts'
    values:
      author: 'rbf'
      layout: 'post'
      lang: 'en'


sass:
    style: compressed

# SOURCE: http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  # profile: true
  # ignore:
  #   envs: [local]